"""empty message

Revision ID: 3729bd0a23df
Revises: 6a6c623e2cf9
Create Date: 2026-05-27 18:47:37.160882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3729bd0a23df'
down_revision = '6a6c623e2cf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.alter_column('character_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('planet_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.alter_column('planet_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('character_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
