"""empty message

Revision ID: 6a6c623e2cf9
Revises: 9cd3f9683c56
Create Date: 2026-05-27 16:39:02.894197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a6c623e2cf9'
down_revision = '9cd3f9683c56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.String(length=80), nullable=False))
        batch_op.create_unique_constraint(None, ['img'])

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.String(length=80), nullable=False))
        batch_op.create_unique_constraint(None, ['img'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('img')

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('img')

    # ### end Alembic commands ###
