"""empty message

Revision ID: c613e172b353
Revises: 363b32821869
Create Date: 2026-05-31 09:25:17.009321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c613e172b353'
down_revision = '363b32821869'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_constraint('character_birth_year_key', type_='unique')
        batch_op.drop_constraint('character_description_key', type_='unique')
        batch_op.drop_constraint('character_gender_key', type_='unique')
        batch_op.drop_constraint('character_height_key', type_='unique')
        batch_op.drop_constraint('character_img_key', type_='unique')

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_constraint('planet_climate_key', type_='unique')
        batch_op.drop_constraint('planet_description_key', type_='unique')
        batch_op.drop_constraint('planet_diameter_key', type_='unique')
        batch_op.drop_constraint('planet_gravity_key', type_='unique')
        batch_op.drop_constraint('planet_img_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.create_unique_constraint('planet_img_key', ['img'])
        batch_op.create_unique_constraint('planet_gravity_key', ['gravity'])
        batch_op.create_unique_constraint('planet_diameter_key', ['diameter'])
        batch_op.create_unique_constraint('planet_description_key', ['description'])
        batch_op.create_unique_constraint('planet_climate_key', ['climate'])

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.create_unique_constraint('character_img_key', ['img'])
        batch_op.create_unique_constraint('character_height_key', ['height'])
        batch_op.create_unique_constraint('character_gender_key', ['gender'])
        batch_op.create_unique_constraint('character_description_key', ['description'])
        batch_op.create_unique_constraint('character_birth_year_key', ['birth_year'])

    # ### end Alembic commands ###
